# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Server
source: docs
destination: _gh_pages
host: 0.0.0.0
port: 9001
url: https://iconsfonts.github.io
baseurl: /docs/3.4
encoding: UTF-8
exclude:
  - assets/less/

# plugins:
  - jekyll-sitemap

# Custom vars
current_version: 3.4.0
docs_version: 3.4
repo: https://github.com/CKurisu/iconsfonts
sass_repo: https://github.com/CKurisu/iconsfonts-sass

# download:
  source: https://github.com/CKurisu/iconsfonts/archive/v3.4.0.zip
  dist: https://github.com/CKurisu/iconsfonts/releases/download/v3.4.0/bootstrap-3.4.0-dist.zip
  sass: https://github.com/CKurisu/iconsfonts-sass/archive/v3.4.0.tar.gz

# blog:             https://blog.getbootstrap.com
# expo:             https://expo.getbootstrap.com
# themes:           https://themes.getbootstrap.com

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css
  css_hash:       "sha384-XqdTYMhEw7L+zMnc2RRxZatc8qMFAA+wGiuovZq4hQ6asWFIqCmb31QPmCWWql8D"
  css_theme:      https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css
  css_theme_hash: "sha384-hC3Ueg6/iOQ2QPtSDrvg1InlVp2zeM+N2VvqRHZ0GOy1Yrt+NWt0AGQ3RJTTPn7S"
  js:             https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js
  js_hash:        "sha384-yyV0wQoeR+3RUXUDBpZKT+/jF14z1kqBmBluzZ0FBluQxi3g7xIsZOByNNu0PNeZ"
